# DEFINICAO LOG DA APLICACAO
logging:
   level:
      com.lucas.usuario-cucumber: DEBUG
      org.springframework: INFO
            
# DEFINICAO BANCO DE DADOS      
spring:
    jpa:
        database: POSTGRESQL
        show-sql: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                temp:
                    use_jdbc_metadata_defaults: false
    datasource:
        platform: postgres
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/cucumber-teste
        username: postgres
        password: postgres
          
campo.obrigatorio: Campo Obrigatorio